spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: web-books
logging:
  level:
    root: WARN
  output:
    ansi:
      enabled: always
server:
  port: 8082
  servlet:
    context-path: /api
