spring:
  datasource:
    url: jdbc:h2:mem:books
  liquibase:
    enabled: true

  output:
    ansi:
      enabled: always
  shell:
    interactive:
      enabled: true

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    org.springframework: ERROR
    ru.otus.spring: ERROR

