version: '3.4'
services:
  mongo-rs0-1:
    image: "mongo-start"
    build: ./mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - mongo-rs0-2
      - mongo-rs0-3
    networks:
      - nw
  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db
    networks:
      - nw
  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27020:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db
    networks:
      - nw
  setup-rs:
    image: "setup-rs"
    build: ./mongo-setup
    depends_on:
      - mongo-rs0-1
    networks:
      - nw
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      DB_HOST: mongo-rs0-2
      DB_PORT: 27017
    networks:
      - nw
    depends_on:
      - setup-rs
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    depends_on:
      - backend
networks:
  nw:
