version: '3.4'
services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    network_mode: 'host'
    depends_on:
        - backend
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    network_mode: 'host'
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
