application:
  locale: ru_RU
  accessible-locales:
    - ru
    - en
    - de

menu:
  items:
    - test.menuitem.text.test
    - test.menuitem.text.exit
    - test.menuitem.text.locale
  commands:
    exit: q
    test: t
  messages:
    title: test.menu.title
    unknownCommand: test.menu.text.unknownCommand
    error: test.error

login:
  messages:
    invite: test.login.invite
    wrongFormat: test.login.wrongFormat
    accessDenied: test.login.accessDenied
    error: test.error

test:
  pass:
    percent: 70
  ask-questions:
    input:
      invite-to-answer: test.process.answer.input
    select:
      invite-to-answer: test.process.answer.select
      answer-repeat-select: test.process.answer.repeatSelect
  process:
    messages:
      comeback: test.process.messages.comeback
      error: test.error
  result:
    messages:
      header: test.result.header
      failed: test.result.failed
      done: test.result.done
      answer: test.result.studentAnswer
      answerRight: test.result.answer.right
      answerWrong: test.result.answer.wrong
      rightAnswers: test.result.rightAnswers
      rightAnswersNotDefined: test.result.rightAnswerNotDefined

questions:
  csv:
    path: /
    prefix-file-name: test-questions

logging:
  level:
    org.springframework: "error"
    ru.otus.spring: "error"

spring:
  output:
    ansi:
      enabled: always