spring:
  datasource:
    url: jdbc:h2:mem:books
  output:
    ansi:
      enabled: always
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    org.springframework: "error"
    ru.otus.spring: "error"

