DROP TABLE IF EXISTS AUTHORS CASCADE;
CREATE TABLE AUTHORS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(255),
    REAL_NAME VARCHAR(255),
    BIRTHDAY  DATE
);
CREATE SEQUENCE AUTHORS_SEQUENCE START 1;

CREATE SEQUENCE GENRES_SEQUENCE START 1;
DROP TABLE IF EXISTS GENRES CASCADE;
CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);


CREATE SEQUENCE BOOKS_SEQUENCE START 1;
DROP TABLE IF EXISTS BOOKS CASCADE;
CREATE TABLE BOOKS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(255),
    ISBN     VARCHAR(50),
    GENRE_ID BIGINT REFERENCES GENRES (ID)
);


DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS
(
    BOOK_ID   BIGINT NOT NULL REFERENCES BOOKS (ID),
    AUTHOR_ID BIGINT NOT NULL REFERENCES AUTHORS (ID),
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID     BIGINT       NOT NULL REFERENCES BOOKS (ID),
    DESCRIPTION VARCHAR(255) NOT NULL
);

