spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/books
      host: localhost
      port: 27017
      database: books
logging:
  level:
    root: ERROR
  output:
    ansi:
      enabled: always
